a = int(input("enter a"))
b = int(input("enter b"))
print(a+b)
print(f"(sum of {a} and {b} = {a+b})")
print(f"(diff of {a} and {b} = {a-b})")
print(f"(product of {a} and {b} = {a*b})")
print(f"(flow of {a} and {b} = {a//b})")
print(f"(division of {a} and {b} = {a/b})")
print(f"modulo of {a} and {b} = {a%b}")
